#include "duco_core.hpp"
#include "exponential/exponential.hpp"
#include "manipulation/manipulation.hpp"
#include "matrix/matrix.hpp"
#include "notation/notation.hpp"
#include "trigonometry/trigonometry.hpp"
#include "vector/functions.hpp"
#include "vector/vector.hpp"
